# @name get-all-prompts

GET http://localhost:3333/prompts

###

# @name get-all-videos

GET http://localhost:3333/videos

###

# @name get-video-by-id

GET http://localhost:3333/videos/b4f9832b-19cd-432b-80fe-9e968cc2a18b

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/8975ae61-b283-489a-8ab7-935908db427f/transcription
Content-Type: application/json

{
    "prompt": "clean architecture, ddd"
}

###

# @name generate-ia-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "8975ae61-b283-489a-8ab7-935908db427f",
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''",
    "temperature": 0.5
}